#!/usr/bin/env node
/**
 * Stages the WebAssembly extractor and the licence texts into apps/web/public/
 * before `next build`, and writes the generated module that tells the app where
 * they landed.
 *
 * Two things this solves, both of which bite on a static host:
 *
 * 1. **Cache correctness.** The .wasm is 465 KB and changes only when the extractor
 *    is rebuilt, so it wants `immutable` caching — but `immutable` on a fixed
 *    filename is a lie that strands returning visitors on an old binary for a year.
 *    Everything therefore goes into `public/wasm/<content-hash>/`, so a new binary
 *    is a new URL and `immutable` is simply true.
 *
 * 2. **Bundler independence.** pubshift.mjs locates its .wasm with
 *    `new URL("pubshift.wasm", import.meta.url)`, and it has a Node branch that
 *    imports `node:module`. Rather than teach webpack about either, the app loads
 *    the module at runtime with a native dynamic `import()` the bundler is told to
 *    leave alone — so the files are copied here verbatim, keeping the `dist/`
 *    subdirectory that index.mjs expects.
 *
 * Run automatically by `npm run build` and `npm run dev` in apps/web.
 */

import { createHash } from 'node:crypto';
import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const WEB = path.resolve(HERE, '..');
const ROOT = path.resolve(WEB, '..', '..');

const WASM_SRC_DIR = path.join(ROOT, 'wasm');
const WASM_BINARY = path.join(WASM_SRC_DIR, 'dist', 'pubshift.wasm');
const WASM_GLUE = path.join(WASM_SRC_DIR, 'dist', 'pubshift.mjs');
const WASM_ENTRY = path.join(WASM_SRC_DIR, 'index.mjs');

const PUBLIC = path.join(WEB, 'public');
const PUBLIC_WASM = path.join(PUBLIC, 'wasm');
const PUBLIC_LICENCES = path.join(PUBLIC, 'licences');
const GENERATED = path.join(WEB, 'lib', 'wasm-asset.ts');

function die(message, remedy) {
  console.error(`\nprepare-assets: ${message}\n`);
  if (remedy) console.error(`${remedy}\n`);
  process.exit(1);
}

for (const [label, file] of [
  ['the WebAssembly binary', WASM_BINARY],
  ['the Emscripten glue', WASM_GLUE],
  ['the loader', WASM_ENTRY],
]) {
  if (!existsSync(file)) {
    die(
      `cannot find ${label} at ${path.relative(ROOT, file)}`,
      'wasm/dist is gitignored, so a fresh checkout has to build it:\n' +
        '  node tools/licence/sources.mjs fetch   # pinned libmspub + librevenge\n' +
        '  ./wasm/build.sh                        # needs emscripten on PATH\n' +
        'Refusing to build a site whose only job is converting files but which ships no converter.',
    );
  }
}

const digest = createHash('sha256').update(readFileSync(WASM_BINARY)).digest('hex');
const build = digest.slice(0, 16);
const target = path.join(PUBLIC_WASM, build);

// Clear stale builds: an immutable directory per binary is only cheap if old ones go.
if (existsSync(PUBLIC_WASM)) {
  for (const name of readdirSync(PUBLIC_WASM)) {
    if (name !== build) rmSync(path.join(PUBLIC_WASM, name), { recursive: true, force: true });
  }
}

mkdirSync(path.join(target, 'dist'), { recursive: true });
cpSync(WASM_ENTRY, path.join(target, 'index.mjs'));
cpSync(WASM_GLUE, path.join(target, 'dist', 'pubshift.mjs'));
cpSync(WASM_BINARY, path.join(target, 'dist', 'pubshift.wasm'));

// The licence obligations travel with the binary, so they are part of the deploy,
// not just of the repository. See docs/DEPLOY.md and THIRD-PARTY-NOTICES.md.
mkdirSync(PUBLIC_LICENCES, { recursive: true });
cpSync(path.join(ROOT, 'LICENSE'), path.join(PUBLIC_LICENCES, 'MPL-2.0.txt'));
const notices = path.join(ROOT, 'THIRD-PARTY-NOTICES.md');
if (existsSync(notices)) {
  cpSync(notices, path.join(PUBLIC_LICENCES, 'THIRD-PARTY-NOTICES.md'));
} else {
  die(
    'THIRD-PARTY-NOTICES.md is missing',
    'Generate it: node tools/licence/sources.mjs notices\n' +
      'It is not optional — it is how recipients of pubshift.wasm are told what is in it.',
  );
}

const pin = JSON.parse(readFileSync(path.join(WASM_SRC_DIR, 'third-party.json'), 'utf8'));
const shipped = pin.components
  .filter((c) => c.obligation === 'source-offer')
  .map((c) => ({ name: c.name, version: c.version, licence: c.licenceTaken ?? c.licence }));

writeFileSync(
  GENERATED,
  `// GENERATED by scripts/prepare-assets.mjs — do not edit, do not commit a stale copy.
//
// The extractor is served from a content-addressed directory so that it can be
// cached immutably: a different binary is a different URL, never a stale one.

/** sha256 of pubshift.wasm, truncated. Also the directory it is served from. */
export const WASM_BUILD = ${JSON.stringify(build)};

/** Full digest, so the page can state exactly which binary it ran. */
export const WASM_SHA256 = ${JSON.stringify(digest)};

/** Absolute URL path of the loader. Imported at runtime, not bundled. */
export const WASM_ENTRY_URL = ${JSON.stringify(`/wasm/${build}/index.mjs`)};

/** MPL-covered libraries compiled into that binary, for the credits page. */
export const SHIPPED_LIBRARIES: ReadonlyArray<{ name: string; version: string; licence: string }> =
  ${JSON.stringify(shipped, null, 2)};
`,
);

const kb = (readFileSync(WASM_BINARY).byteLength / 1024).toFixed(0);
console.log(`prepare-assets: wasm ${kb} KB -> public/wasm/${build}/`);
console.log(`prepare-assets: licences -> public/licences/`);
