/**
 * The Content Security Policy, written once.
 *
 * The whole product is "your document never leaves this tab". `connect-src 'self'`
 * is that promise written somewhere the browser enforces it: if any dependency ever
 * tries to POST a file anywhere, the request fails instead of succeeding quietly.
 * `wasm-unsafe-eval` is what lets the Publisher reader instantiate; `blob:` covers
 * the worker and the page previews, both of which are built in memory from the
 * user's own file.
 *
 * ## Why the policy is shipped twice
 *
 * A CSP can arrive two ways, and neither one alone is enough here.
 *
 * As an **HTTP header** it is the complete policy — but `output: 'export'` produces
 * a directory of files with no server left to add a header, so the header exists
 * only where the host is told about it separately: `_headers` (Cloudflare Pages,
 * Netlify) and `vercel.json`, both generated by `scripts/emit-host-config.mjs`.
 * On S3, nginx, GitHub Pages or any other plain static host those files are inert
 * and no policy at all would apply.
 *
 * As a **`<meta http-equiv>`** in the document head it travels inside the HTML, so
 * it applies on every host with no server configuration whatsoever. The cost is that
 * `frame-ancestors`, `report-uri`/`report-to` and `sandbox` are ignored when
 * delivered that way (CSP Level 3, §3.3) — but `connect-src` and `form-action`, the
 * two that carry the product's central claim, are enforced normally.
 *
 * So: meta everywhere, header as well wherever a header is possible, and both built
 * from `cspDirectives()` below so the two can never drift. `app/privacy/page.tsx`
 * describes this split to the visitor and must be corrected in the same commit as
 * any change here — the accuracy of that page is the product's only real asset.
 *
 * Plain `.mjs` on purpose: `next.config.mjs` is loaded by Node before any TypeScript
 * exists, and `app/layout.tsx` is bundled by webpack. Both can import this file.
 */

/**
 * Directives a `<meta>`-delivered policy is required to ignore. Leaving them in
 * would not be dangerous — the browser drops them — but it logs a console warning
 * on every page load, and a security warning nobody reads is a security warning
 * that has stopped working.
 */
const META_CANNOT_CARRY = new Set(['frame-ancestors', 'report-uri', 'report-to', 'sandbox']);

/**
 * @param {{ dev?: boolean }} [options]
 * @returns {string[]} one directive per entry, each `name value…`.
 */
export function cspDirectives(options = {}) {
  const dev = options.dev === true;
  return [
    "default-src 'self'",
    // `unsafe-eval` only in development: the dev server's hot reloading needs it and
    // there is no visitor to protect. A production build never contains it.
    `script-src 'self' 'unsafe-inline' 'wasm-unsafe-eval' blob:${dev ? " 'unsafe-eval'" : ''}`,
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data: blob:",
    "font-src 'self' data:",
    // The load-bearing one.
    "connect-src 'self' blob:",
    "worker-src 'self' blob:",
    "object-src 'none'",
    "base-uri 'self'",
    "form-action 'none'",
    // Header only; see META_CANNOT_CARRY.
    "frame-ancestors 'none'",
  ];
}

/** The complete policy, for the `Content-Security-Policy` HTTP header. */
export function cspHeaderValue(options = {}) {
  return cspDirectives(options).join('; ');
}

/** The same policy minus the directives a meta tag may not carry. */
export function cspMetaValue(options = {}) {
  return cspDirectives(options)
    .filter((directive) => !META_CANNOT_CARRY.has(directive.split(/\s+/, 1)[0] ?? ''))
    .join('; ');
}

/** What the meta copy leaves to the header copy. Used by the privacy page's wording. */
export function cspMetaOmits(options = {}) {
  return cspDirectives(options)
    .filter((directive) => META_CANNOT_CARRY.has(directive.split(/\s+/, 1)[0] ?? ''))
    .map((directive) => directive.split(/\s+/, 1)[0] ?? '');
}
